In [140]:
import pandas as pd

# Importando Dados

In [141]:
path = "https://raw.githubusercontent.com/alura-cursos/ML_Classificacao_por_tras_dos_panos/main/Dados/Customer-Churn.csv"

In [142]:
dados = pd.read_csv(path)

dados.head()

Maior65Anos Conjuge Dependentes  MesesDeContrato TelefoneFixo  \
0            0     Sim         Nao                1          Nao   
1            0     Nao         Nao               34          Sim   
2            0     Nao         Nao                2          Sim   
3            0     Nao         Nao               45          Nao   
4            0     Nao         Nao                2          Sim   

  VariasLinhasTelefonicas ServicoDeInternet SegurancaOnline BackupOnline  \
0    SemServicoTelefonico               DSL             Nao          Sim   
1                     Nao               DSL             Sim          Nao   
2                     Nao               DSL             Sim          Sim   
3    SemServicoTelefonico               DSL             Sim          Nao   
4                     Nao       FibraOptica             Nao          Nao   

  SeguroNoDispositivo SuporteTecnico TVaCabo StreamingDeFilmes TipoDeContrato  \
0                 Nao            Nao     Nao               Nao    Mensalmente   
1                 Sim            Nao     Nao               Nao          UmAno   
2                 Nao            Nao     Nao               Nao    Mensalmente   
3                 Sim            Sim     Nao               Nao          UmAno   
4                 Nao            Nao     Nao               Nao    Mensalmente   

  PagamentoOnline FormaDePagamento  ContaMensal Churn  
0             Sim    ChequeDigital        29.85   Nao  
1             Nao      ChequePapel        56.95   Nao  
2             Sim      ChequePapel        53.85   Sim  
3             Nao    DebitoEmConta        42.30   Nao  
4             Sim    ChequeDigital        70.70   Sim

In [143]:
dados.shape

(7043, 18)

# Variáveis

In [144]:
dados.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7043 entries, 0 to 7042
Data columns (total 18 columns):
 #   Column                   Non-Null Count  Dtype  
---  ------                   --------------  -----  
 0   Maior65Anos              7043 non-null   int64  
 1   Conjuge                  7043 non-null   object 
 2   Dependentes              7043 non-null   object 
 3   MesesDeContrato          7043 non-null   int64  
 4   TelefoneFixo             7043 non-null   object 
 5   VariasLinhasTelefonicas  7043 non-null   object 
 6   ServicoDeInternet        7043 non-null   object 
 7   SegurancaOnline          7043 non-null   object 
 8   BackupOnline             7043 non-null   object 
 9   SeguroNoDispositivo      7043 non-null   object 
 10  SuporteTecnico           7043 non-null   object 
 11  TVaCabo                  7043 non-null   object 
 12  StreamingDeFilmes        7043 non-null   object 
 13  TipoDeContrato           7043 non-null   object 
 14  PagamentoOnline         

In [145]:
#modificação de forma manual 
traducao_dic = {'Sim': 1, 
                'Nao': 0}

dadosmodificados = dados[['Conjuge', 'Dependentes', 'TelefoneFixo', 'PagamentoOnline', 'Churn']].replace(traducao_dic)
dadosmodificados.head()

Conjuge  Dependentes  TelefoneFixo  PagamentoOnline  Churn
0        1            0             0                1      0
1        0            0             1                0      0
2        0            0             1                1      1
3        0            0             0                0      0
4        0            0             1                1      1

In [146]:
#transformação pelo get_dummies
dummie_dados = pd.get_dummies(dados.drop(['Conjuge', 'Dependentes', 'TelefoneFixo', 'PagamentoOnline', 'Churn'],
                axis=1))

#junção dos dados trasformados com os que já tinhamos
dados_final = pd.concat([dadosmodificados, dummie_dados], axis=1)

In [147]:
dados_final.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7043 entries, 0 to 7042
Data columns (total 39 columns):
 #   Column                                        Non-Null Count  Dtype  
---  ------                                        --------------  -----  
 0   Conjuge                                       7043 non-null   int64  
 1   Dependentes                                   7043 non-null   int64  
 2   TelefoneFixo                                  7043 non-null   int64  
 3   PagamentoOnline                               7043 non-null   int64  
 4   Churn                                         7043 non-null   int64  
 5   Maior65Anos                                   7043 non-null   int64  
 6   MesesDeContrato                               7043 non-null   int64  
 7   ContaMensal                                   7043 non-null   float64
 8   VariasLinhasTelefonicas_Nao                   7043 non-null   uint8  
 9   VariasLinhasTelefonicas_SemServicoTelefonico  7043 non-null   u

# K-Nearest Neighbours (KNN)

Algoritmo de machine learning. Pode ser usado para tarefas de regressão e classificação.

1. Recebe as informações
2. Calcula as distâncias
3. Ordena da menor para a maior distância
4. Faz uma contagem de classes
5. Classifica a partir dos k-vizinhos mais próximos

k muito pequeno -> Overfitting<br>
k muito grande  -> Underfitting

In [148]:
X = dados_final.drop(columns=['Churn'])
y = dados_final['Churn']

In [149]:
X.iloc[0], y[0]

(Conjuge                                          1.00
 Dependentes                                      0.00
 TelefoneFixo                                     0.00
 PagamentoOnline                                  1.00
 Maior65Anos                                      0.00
 MesesDeContrato                                  1.00
 ContaMensal                                     29.85
 VariasLinhasTelefonicas_Nao                      0.00
 VariasLinhasTelefonicas_SemServicoTelefonico     1.00
 VariasLinhasTelefonicas_Sim                      0.00
 ServicoDeInternet_DSL                            1.00
 ServicoDeInternet_FibraOptica                    0.00
 ServicoDeInternet_Nao                            0.00
 SegurancaOnline_Nao                              1.00
 SegurancaOnline_SemServicoDeInternet             0.00
 SegurancaOnline_Sim                              0.00
 BackupOnline_Nao                                 0.00
 BackupOnline_SemServicoDeInternet                0.00
 BackupOnl

In [150]:
from sklearn.preprocessing import StandardScaler

In [151]:
norm = StandardScaler()

X = norm.fit_transform(X.values)

In [152]:
X[0]

array([ 1.03453023, -0.65401193, -3.05401039,  0.8297975 , -0.43991649,
       -1.27744458, -1.16032292, -0.96332984,  3.05401039, -0.85417615,
        1.38171215, -0.88565976, -0.52592737,  1.00669571, -0.52592737,
       -0.63393298, -0.88361972, -0.52592737,  1.3782406 ,  1.12942721,
       -0.52592737, -0.72396752,  1.0138687 , -0.52592737, -0.63943864,
        1.2273572 , -0.52592737, -0.79013171,  1.23648892, -0.52592737,
       -0.79607014, -0.56297505,  0.90418382, -0.51424938, -0.52504733,
        1.40641839, -0.54480692, -0.5298852 ])

In [153]:
Xmaria = [[0,0,1,1,0,0,39.90,1,0,0,0,1,0,1,0,0,0,0,1,1,1,0,0,1,0,1,0,0,0,0,1,0,0,1,0,0,0,1]]

In [154]:
Xmaria = norm.transform(Xmaria)

Xmaria

array([[-0.96662231, -0.65401193,  0.32743831,  0.8297975 , -0.43991649,
        -1.31816495, -0.82630172,  1.03806605, -0.32743831, -0.85417615,
        -0.72373975,  1.12910177, -0.52592737,  1.00669571, -0.52592737,
        -0.63393298, -0.88361972, -0.52592737,  1.3782406 ,  1.12942721,
         1.90140322, -0.72396752, -0.98632101,  1.90140322, -0.63943864,
         1.2273572 , -0.52592737, -0.79013171, -0.80874158, -0.52592737,
         1.25617071, -0.56297505, -1.1059698 ,  1.94458183, -0.52504733,
        -0.71102597, -0.54480692,  1.88720123]])

In [155]:
import numpy as np

In [156]:
a = Xmaria
b = X[0]

#### Distância Euclidiana

$\sqrt{\sum^{n}_{i=1} (a_i - b_i)^2}$

In [157]:
a - b

array([[-2.00115254,  0.        ,  3.3814487 ,  0.        ,  0.        ,
        -0.04072036,  0.3340212 ,  2.00139589, -3.3814487 ,  0.        ,
        -2.10545189,  2.01476153,  0.        ,  0.        ,  0.        ,
         0.        ,  0.        ,  0.        ,  0.        ,  0.        ,
         2.42733059,  0.        , -2.00018971,  2.42733059,  0.        ,
         0.        ,  0.        ,  0.        , -2.0452305 ,  0.        ,
         2.05224086,  0.        , -2.01015362,  2.45883121,  0.        ,
        -2.11744436,  0.        ,  2.41708643]])

In [158]:
np.square(a - b)

array([[4.00461149e+00, 0.00000000e+00, 1.14341953e+01, 0.00000000e+00,
        0.00000000e+00, 1.65814802e-03, 1.11570160e-01, 4.00558550e+00,
        1.14341953e+01, 0.00000000e+00, 4.43292768e+00, 4.05926401e+00,
        0.00000000e+00, 0.00000000e+00, 0.00000000e+00, 0.00000000e+00,
        0.00000000e+00, 0.00000000e+00, 0.00000000e+00, 0.00000000e+00,
        5.89193381e+00, 0.00000000e+00, 4.00075888e+00, 5.89193381e+00,
        0.00000000e+00, 0.00000000e+00, 0.00000000e+00, 0.00000000e+00,
        4.18296779e+00, 0.00000000e+00, 4.21169253e+00, 0.00000000e+00,
        4.04071758e+00, 6.04585093e+00, 0.00000000e+00, 4.48357062e+00,
        0.00000000e+00, 5.84230682e+00]])

In [159]:
np.sum(np.square(a - b))

84.07574038273466

In [160]:
np.sqrt(np.sum(np.square(a - b)))

9.169282435541762

Essa é a distância da Maria com o Cliente 0 da base

#### Distância Mamhattan

$\sum^{n}_{i=1} |a_i - b_i|$

In [161]:
np.sum(np.abs(a - b))

35.216238687149996

#### Distância Minkowski

$\sqrt[m]{\sum^{n}_{i=1} (a_i - b_i)^m}$

Sendo assim a disntância euclidiana é um caso particular em que m = 2

#### Distância Chebyshev

$max(|a_1-b_1|,~...,~|a_n-b_n|)$

In [162]:
np.max(np.abs(a - b))

3.3814487011790924

In [163]:
from sklearn.model_selection import train_test_split

In [164]:
X_treino, X_teste, y_treino, y_teste = train_test_split(X, y, test_size=0.3, random_state=123)

In [165]:
from sklearn.neighbors import KNeighborsClassifier

In [166]:
knn = KNeighborsClassifier(metric='euclidean')

knn

KNeighborsClassifier(metric='euclidean')

In [167]:
knn.fit(X_treino, y_treino)

KNeighborsClassifier(metric='euclidean')

In [168]:
predito_knn = knn.predict(X_teste)

predito_knn

array([1, 0, 0, ..., 0, 0, 0])

# Bernoulli Naive Bayes

### Teorema de Bayes
<img src="./figures/naive_bayes.png">

### Multivariada de Bernoulli
Usada para calcular a verossimilhança em casos binários

<img src="./figures/bernoulli.png">

In [169]:
from sklearn.naive_bayes import BernoulliNB

In [170]:
np.median(X_treino)

-0.5259273725834717

In [171]:
# binarize transforma valores acima de um limiar em 1 e abaixo em 0
bnb = BernoulliNB(binarize=np.median(X_treino))

bnb

BernoulliNB(binarize=-0.5259273725834717)

In [172]:
bnb.fit(X_treino, y_treino)

BernoulliNB(binarize=-0.5259273725834717)

In [173]:
predito_bnb = bnb.predict(X_teste)

predito_bnb

array([1, 0, 0, ..., 0, 1, 0])

# Decision Tree

Vantagens:
- Não obrigatório tratamento dos dados
- Não necessidade de transformar categóricas em numéricas

Desvantagens:
- Facilidade de Overfitting
- Instabilidade de crescimento

<img src="./figures/tree.png">

#### Critérios de divisão de nós

- Índice Gini
  - Quanto mais próximo de 1 indica que o dado é menos homogêneo
  - O menor índice é selecionado para começar a árvore
- Qui-Quadrado
- Ganho de informção (entropia)
  - Quanto maior a entropia, mais desordenado está o dado
- Redução na variância

In [174]:
from sklearn.tree import DecisionTreeClassifier

In [175]:
dtc = DecisionTreeClassifier(criterion='entropy', random_state=42)

dtc

DecisionTreeClassifier(criterion='entropy', random_state=42)

In [176]:
dtc.fit(X_treino, y_treino)

DecisionTreeClassifier(criterion='entropy', random_state=42)

In [177]:
dtc.feature_importances_

array([0.03168742, 0.01862901, 0.00064085, 0.02675693, 0.0208788 ,
       0.2056003 , 0.29546501, 0.0061786 , 0.00273035, 0.00747536,
       0.        , 0.04908356, 0.        , 0.01609395, 0.        ,
       0.00722833, 0.01220706, 0.        , 0.01248286, 0.01138295,
       0.0006673 , 0.0095669 , 0.01841631, 0.        , 0.00650511,
       0.00385849, 0.        , 0.00666929, 0.00517146, 0.        ,
       0.00665371, 0.00473251, 0.15803541, 0.00348686, 0.01414378,
       0.01601964, 0.01064163, 0.01091026])

In [178]:
predito_dtc = dtc.predict(X_teste)

predito_dtc

array([1, 0, 0, ..., 1, 0, 0])

# Matriz de confusão

In [179]:
from sklearn.metrics import confusion_matrix

### K-Nearest Neighbours

In [180]:
print(confusion_matrix(y_teste, predito_knn))

[[1305  218]
 [ 317  273]]


### Bernoulli Naive Bayes

In [181]:
print(confusion_matrix(y_teste, predito_bnb))

[[1051  472]
 [ 116  474]]


### Decision Tree Classifier

In [182]:
print(confusion_matrix(y_teste, predito_dtc))

[[1249  274]
 [ 290  300]]


## Acurácia

In [183]:
from sklearn.metrics import accuracy_score

### K-Nearest Neighbours

In [184]:
acuracia_knn = accuracy_score(y_teste, predito_knn)

acuracia_knn

0.7468054898248935

### Bernoulli Naive Bayes

In [185]:
acuracia_bnb = accuracy_score(y_teste, predito_bnb)

acuracia_bnb

0.7217226691907241

### Decision Tree Classifier

In [186]:
acuracia_dtc = accuracy_score(y_teste, predito_dtc)

acuracia_dtc

0.7330809275911027

#### Geral

In [187]:
acuracia = [acuracia_knn, acuracia_bnb, acuracia_dtc]

## Precisão

In [188]:
from sklearn.metrics import precision_score

### K-Nearest Neighbours

In [189]:
precisao_knn = precision_score(y_teste, predito_knn)

precisao_knn

0.5560081466395111

### Bernoulli Naive Bayes

In [190]:
precisao_bnb = precision_score(y_teste, predito_bnb)

precisao_bnb

0.5010570824524313

### Decision Tree Classifier

In [191]:
precisao_dtc = precision_score(y_teste, predito_dtc)

precisao_dtc

0.5226480836236934

#### Geral

In [192]:
precisao = [precisao_knn, precisao_bnb, precisao_dtc]

## Recall

In [193]:
from sklearn.metrics import recall_score

### K-Nearest Neighbours

In [194]:
recall_knn = recall_score(y_teste, predito_knn)

recall_knn

0.46271186440677964

### Bernoulli Naive Bayes

In [195]:
recall_bnb = recall_score(y_teste, predito_bnb)

recall_bnb

0.8033898305084746

### Decision Tree Classifier

In [196]:
recall_dtc = recall_score(y_teste, predito_dtc)

recall_dtc

0.5084745762711864

#### Geral

In [197]:
recall = [recall_knn, recall_bnb, recall_dtc]

# Comparações de desempenhos

In [198]:
desempenhos = pd.DataFrame({
  'Acurácia': acuracia,
  'Precisão': precisao,
  'Recall':   recall
}, index=['KNN', 'BNB', 'DTC'])

desempenhos

Acurácia  Precisão    Recall
KNN  0.746805  0.556008  0.462712
BNB  0.721723  0.501057  0.803390
DTC  0.733081  0.522648  0.508475